### PR TITLE
Add support for Java 17

### PR DESCRIPTION
**Pull request by skylee03**
- Update Spark to 3.3.3
- Specify Netty and Jackson versions
- Add `--add-opens` JVM options to get rid of "cannot access class" errors
- Update tests to adapt the output format of Spark 3.3.3

### CODE REVIEW

**Comment by anthony-khong** [comment]
Thanks for this @skylee03, I wasn't expecting this! I'm not sure why the Actions are not running. I'll try to find a way to run it, and if all the checks pass, then let's merge it!

**Comment by anthony-khong** [comment]
I'm going to try and close and reopen this as I changed some of the Actions config.

**Comment by anthony-khong** [comment]
@skylee03 I hope the failing test should be easy-ish to fix?

Also, would you be happy to make the same `project.clj` changes to the Lein template in `lein-template/resources/leiningen/new/geni/project.clj` as well?

**Comment by skylee03** [comment]
> @skylee03 I hope the failing test should be easy-ish to fix?
> 
> Also, would you be happy to make the same `project.clj` changes to the Lein template in `lein-template/resources/leiningen/new/geni/project.clj` as well?

👌

**Comment by skylee03** [comment]
I found that some dependencies in `lein-template/resources/leiningen/new/geni/project.clj` are newer than those in `project.clj`. Should I also update the dependencies in `project.clj` to the same versions?

**Comment by anthony-khong** [comment]
Yes, please, if you could that, that would be fantastic, thanks! Happy to merge this after that.

**Comment by anthony-khong** [comment]
Thank you again for your contribution! I'll prepare a 0.0.41 release.

**Pull request merged**
