### PR TITLE
Managed tables

### PR DESCRIPTION
**Pull request by erp12**
This is a work-in-progress PR intended to get feedback on the API and create a place for discussion around spark session management for tests. As of the creation of the ticket, this version is passing tests with `lein midje` on my local machine but failing `make ci`.

This PR changes more files than I originally expected. If it is too extreme of a change, I would be happy to take a different approach.

### Background

Spark has two stateful locations that are used to manage tables when running locally.

1. The `spark_warehouse` is a directory specified by the session setting `spark.sql.warehouse.dir`. This is the location where every table's data files are stored.

2. The metastore is an in-memory database that stores metadata about each table (its location, etc.) 

Once we add the capability to read/write tables, our testing pattern must clear the state in these two places. If we have that, test expectations become, order independent, idempotent, generally easier to reason about. Also, we don't want to accumulate test tables on disk over time.

### Possible patterns (please flag anything I forgot!)

1. Dropping all managed tables between tests using SQL. This doesn't immediately delete the data in the warehouse. Relying on this alone leads to semi-random file-already-exists errors.

2. Deleting the warehouse directory between tests. This doesn't immediately delete the data in the metastore. Relying on this alone leads to semi-random table-already-exists errors.

3. Change the `spark.sql.warehouse.dir` between tests. Spark does not allow changing session level settings of an active spark session. The spark session must be stopped and a new one must be started.

In my other projects (and this PR) I leverage a combination of approach 3 and 2. For tests that touch managed tables, the session is restarted with a new `spark.sql.warehouse.dir` during "setup" and the warehouse directory is deleted during "tear-down". 

I am happy to go a different direction, if we can find one.

### Impact on the rest of the code-bsae.

There are 2 main changes that had to made in throughout the Geni codebase. 

1. The default spark session at `zero-one.geni.defaults/spark` was changed to an `atom` instead of `delay`. This may negatively impact the startup time, but I didn't measure it.

   This allows the spark session to be replaced by a new one with a different warehouse directory.

   My original design was to leave `zero-one.geni.defaults/spark` as a `delay` and use a different session for tests. The second session would be stored in an `atom` in `test-resources`. This ended up being a challenging approach because it became critical that the `defaults/spark` session delay not be touched throughout tests. It might be work revisiting this idea and spend more time stomping out any reference to `zero-one.geni.defaults/spark` in the tests.

2. Old spark session can't leak between tests. For example, the Datasets in `test-resources` are created with the initial spark session. If that session is closed between tests, the Dataset becomes unreadable.

   To address this, I changed all the test-resources to functions that create a new Dataset using the current spark session in the atom.

@anthony-khong I would like to get your thoughts before I flesh out the tests. Also, any input on the `make ci` failure would be much appreciated. That one currently has me stumped, but I will keep working on it.

### CODE REVIEW

**Comment by erp12** [comment]
Interesting... the tests in CI seemed to pass! 😅 When I run `make ci` I get an exception in the spark session builder. I guess that is just another local problem for me. 

I will work on getting coverage up to 100% and fixing the issues raised by the linter.

**Comment by anthony-khong** [comment]
Hi Eddie, thanks for this PR! It looks awesome!! Please give me until the end of the weekend to fully study it and give feedback!

As for why `lein midje` works, but not `make ci`, I believe it's because the coverage threshold is set at 99%, whereas at the moment it's at 98%. So yes, putting some tests there would address the issue! I believe `clj-kondo` is failing as well because of some unused requires/imports.

**Comment by anthony-khong** [comment]
Hi Eddie, I've managed to look through your comments and the changes. It honestly looks great!!

> In my other projects (and this PR) I leverage a combination of approach 3 and 2. For tests that touch managed tables, the session is restarted with a new spark.sql.warehouse.dir during "setup" and the warehouse directory is deleted during "tear-down".

As long as the `coverage` job takes under 5 minutes on GitHub, I believe it's fine. I see that the job failed in 3 minutes, so I believe this shouldn't be a big deal. (I actually didn't know that that's how Spark works under the hood! You learn something new everyday! Thank you!)

> The default spark session at zero-one.geni.defaults/spark was changed to an atom instead of delay. This may negatively impact the startup time, but I didn't measure it.

I'll look into how it impacts the startup time. My guess is that it has no impact, because on the `main` namespace, it's already futured.

> To address this, I changed all the test-resources to functions that create a new Dataset using the current spark session in the atom.

Sounds like a very sensible idea, and the code change is minimal. I think the number of files changed is a lot, but it's all pretty straightforward. I think it's good to merge as soon as the CI pipeline passes! (You may have to resolve some conflicts, as I added docs to some of these namespaces, but it should be straightforward! 🤞 )

Again, thank you so much for looking at this! It's super awesome!

**Comment by erp12** [comment]
Sorry for the slow progress. I have gotten full coverage on the catalog code in my local branch and I am just doing some final refactoring and adding comments. I should have a final version in the next day or two.

**Comment by anthony-khong** [comment]
Hi Eddie, absolutely! This is a great addition to the library, please do not feel pressured to deliver it quickly! I'm very grateful that you're working on it in the first place! 🙏

**Comment by anthony-khong** [comment]
Hi Eddie, this looks really good!! I can't say that I've understood everything here, but it looks good to me!

A couple of quick questions:
- Out of curiosity, what is the difference between `atom` and `delay` (or `future`) in this case? Just curious what makes one work, but not the other.
- Would `[zero-one.geni.catalog :as c]` be used by someone using the library? Or they just need to know `read-table!` and `write-table!`. I've been trying to keep the number of to-be-required namespaces small, say only `core`, `ml`, `rdd` and `streaming` (i.e. mirroring the four main Spark modules). If we need stuff from `catalog`, should we do `import-var` to `core`?
- The coverage is at 99% at the moment, which is absolutely fine! I'd be very happy to attempt to cover the rest, but I'm wondering if these involve the midje edge cases you spoke about?

This is a massive PR, thank you so much for your work!

EDIT: I saw where the coverage misses are, it's all minor. I'm happy to make it back to 100%!

**Comment by erp12** [comment]
Thanks for merging! I'm happy to help with this awesome tool. Those are good questions.
__________________________

Regarding `atom` vs `delay`, the reason is that there are rare edge cases (like testing) where you will be creating a new Spark session. See [this function](https://github.com/zero-one-group/geni/pull/243/files#diff-1001ee8029c7cdfd648448848efdc277694f3b47ff369e0a13543a0f37686ce9R76-R82) for an example of replacing the session in the atom with a new one. As far as I know, it is not possible to replace the value inside of a `delay`.

Why do we need to do this? Well... for bettor or worse, the `SparkSession` is a singleton. There can only be either zero or one instance _per jvm_ 🤢 . If we build a new one while any other session is still active, we will get a reference to the active one. This presents a problem when each test suite tries to use a a fresh spark session that has an empty metastore and warehouse. Before we can create a fresh session, we need to close the old session and make sure that there are no references to it. If we use a `delay`, the session that gets created on the initial dereference will be the only spark session that can be created. If we use an `atom`, we can close the session in the atom and `reset!` with a new session.

This is an area of Spark that really bothers me. I definitely don't understand spark session management fully, and I still see behavior that surprises me from time to time. ¯\\_(ツ)_/¯ 
___________________________

For the catalog API, I suppose I would call it a user-level abstraction, although some users may never need it. As you mentioned, reading and writing tables doesn't require use of the catalog functions. The catalog is mostly used to answer questions like:

- What databases/tables/views/columns exist?
- Is a table cached?
- What is the current database?
- Is this "table" name associated with an actual table, or just a view?

And to perform basic management of the tables (dropping, caching, changing database, etc) which is required to build framework/platform code around spark tables. The counterpart for writing data into S3 or HDFS would be the file system utility that let's you do things like:

- list out what directories exist under a certain root to determine which datasets exist in that location.
- Delete a folder associated with a parquet dataset.

Advanced users may prefer to build on top of apache Hive interfaces directly instead of Spark's catalog. Spark only natively covers the basics of table management.

I like your plan to mirror the spark modules. I would support moving `catalog` under `zero-one.geni.core` and `import-var` to `core`.

**Comment by anthony-khong** [comment]
Hi Eddie, thank you for the explanation. It's very clear. It sounds like the swap to `atom` is indeed required. And I checked the startup time - there's zero impact, so there's absolutely no downsides!

As for the catalog, I'll open an issue for myself. Should be quick to do, as it's just a matter of doing `import-var` + making docstrings.

> I like your plan to mirror the spark modules. I would support moving catalog under zero-one.geni.core and import-var to core.

As for this, yes, it's a bit of a pet peeve of mine 😅 I like the kind of catch-all imports such as `import pandas as pd`, which basically gives you all the powers you need, and not have to do several requires to accomplish one task.

**Pull request merged**
